src/objects/Answers__c.object
<CustomObject>
    <fields>
        <fullName>CorrectAnswer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Correct Answer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyResponse__c</fullName>
        <label>Survey Response</label>
        <referenceTo>SurveyResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextfieldAnswer__c</fullName>
        <label>TextfieldAnswer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Choice_A__c</fullName>
        <label>Choice A</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_B__c</fullName>
        <label>Choice B</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_C__c</fullName>
        <label>Choice C</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_D__c</fullName>
        <label>Choice D</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_E__c</fullName>
        <label>Choice E</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CorrectAnswer__c</fullName>
        <description>The correct answer for the exam question</description>
        <label>Correct Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questionfor__c</fullName>
        <description>Pick list field to determine what the question is for. Example: Survey question or exam question</description>
        <label>Question for</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Exam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Radio</fullName>
        <active>true</active>
        <label>Radio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>NumberofQuestions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of questions the test taker will see</description>
        <label>Number of Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Surveys Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>Exam</fullName>
        <active>true</active>
        <description>A survey record type that represents an exam format</description>
        <label>Exam</label>
    </recordTypes>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <description>the default record type for survey</description>
        <label>Survey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyJoinQuestion__c.object
<CustomObject>
    <description>The junction object between the survey object and question object</description>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Junction</relationshipLabel>
        <relationshipName>QuestionJunction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Junction</relationshipLabel>
        <relationshipName>SurveyJunction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Join Question</label>
    <nameField>
        <displayFormat>SJQ-{00000000}</displayFormat>
        <label>Survey Join Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Join Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <fields>
        <fullName>ContactName__c</fullName>
        <formula>Contact__r.FirstName+&quot; &quot;+Contact__r.LastName</formula>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExamScore__c</fullName>
        <label>Exam Score</label>
        <summaryFilterItems>
            <field>Answers__c.CorrectAnswer__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answers__c.SurveyResponse__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Filled Out</fullName>
                </value>
                <value>
                    <fullName>Not Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DynamicSurveyResponseExtension.cls
public with sharing class DynamicSurveyResponseExtension {
    
    private static final String TRUE_FALSE_TYPE = 'True/False';
    private static final String MULTIPLE_CHOICE_TYPE = 'Multiple Choice';
    private static final String RADIO_TYPE = 'Radio';
    private static final String TEXT_TYPE = 'Short Answer';
    
    
    public SurveyResponse__c resp{get;set;}
    public integer numQuestions{get;set;}
    public integer examScore{get;set;}
    public String sname{get;set;}
    public Survey__c surv{get;set;}
    public Map<Question__c,Answers__c> mapResp {get;set;}
    List<SurveyJoinQuestion__c> joins {get;set;}
    public boolean isFilled{get;set;}
    public boolean isExam{get;set;}
    public Map<String,String> responseByQuestionId{get;set;} // stores answers to questions. short answer, radio, true/false
    public Map<String,List<String>> selectedOptionsByQuestionId{get;set;} // stores answers to multiple choice questions
    public Map<String,List<SelectOption>> availableOptionsByQuestionId{get;set;} // used to fill available options on the form
    public Map<String,String> answerMap{get;set;}
    public List<Question__c> questions{get;set;}
    
    
    public DynamicSurveyResponseExtension(ApexPages.StandardController stdController){
        
        Id respId = (Id)stdController.getRecord().id;
        resp = [select id,name,Survey__c,Survey_Status__c,ExamScore__c,ContactName__c,(select id,name,Question__c,TextfieldAnswer__c from Answers__r) from SurveyResponse__c where id =: respId limit 1];
        surv = [select id,name,RecordType.Name,NumberofQuestions__c from Survey__c where id =: resp.Survey__c];
        sname = surv.name;
        mapResp = new Map<Question__c,Answers__c>();  
        //joins = [SELECT Id, Question__r.Id,Question__r.CorrectAnswer__c,Question__r.Questionfor__c,Question__r.RecordTypeId, Question__r.Choice_A__c, Question__r.Choice_B__c, Question__r.Choice_C__c, Question__r.Choice_D__c, Question__r.Choice_E__c, Question__r.Question_Text__c, Question__r.RecordType.Name FROM SurveyJoinQuestion__c WHERE Survey__r.Id = :resp.Survey__c];
        
        isFilled = false;
        isExam = false;
        responseByQuestionId = new Map<String,String>();
        selectedOptionsByQuestionId = new Map<String,List<String>>();
        availableOptionsByQuestionId = new Map<String,List<SelectOption>>();
        answerMap = new Map<String,String>();
        questions = new List<Question__c>();
        
        if(resp.Survey_Status__c =='Filled Out'|| resp.Answers__r.size() > 0){
        	if(surv.RecordType.Name == 'Exam' && surv.NumberofQuestions__c > 0){
        		setupSelectedAnswers();
        	}else{
	            setupAnswers();
        	}
        	isFilled = true;
        }
        
        if(surv.RecordType.Name == 'Exam'){
        	examScore = Integer.valueOf(resp.ExamScore__c);
        	isExam = true;
        }
        
        numQuestions = questions.size();
        
    }
   @TestVisible
    private void setupSelectedAnswers(){
    	
        List<Answers__c> existingAnswers = [
                SELECT Id, Question__c, TextfieldAnswer__c,Question__r.Id,Question__r.CorrectAnswer__c,Question__r.Questionfor__c,Question__r.RecordTypeId, Question__r.Choice_A__c, Question__r.Choice_B__c, Question__r.Choice_C__c, Question__r.Choice_D__c, Question__r.Choice_E__c, Question__r.Question_Text__c, Question__r.RecordType.Name
                FROM Answers__c
                WHERE SurveyResponse__c = :resp.Id
        ];
        
        //List<Question__c> questions = new List<Question__c>();
        for(Answers__c j : existingAnswers){
            questions.add(j.Question__r);
        }
        
        Map<Id, Answers__c> existingAnswersByQuestionId = new Map<Id, Answers__c>();
        for(Answers__c answer : existingAnswers){
            existingAnswersByQuestionId.put(answer.Question__c, answer);
        }

        for(Question__c q : questions) {
            Answers__c answer;
            if (existingAnswersByQuestionId.containsKey(q.Id)) {
                answer = existingAnswersByQuestionId.get(q.Id);
            
                if (q.RecordType.Name == MULTIPLE_CHOICE_TYPE) {
                    //List<String> selectedChoices = answer.MultipleChoiceOutput__c.split(',');
                    List<String> selectedChoices = answer.TextfieldAnswer__c.split('\\|');
                    selectedOptionsByQuestionId.put(q.Id, selectedChoices);
                } else {
                    if(answer.TextfieldAnswer__c != null)
                        responseByQuestionId.put(q.Id, answer.TextfieldAnswer__c);
                }
            }
        }
	
    }
    
    
    private void setupAnswers(){
        SurveyResponse__c surveyResponse = resp;
        
        List<SurveyJoinQuestion__c> joins = [
            SELECT Id, Question__r.RecordTypeId, Question__r.Choice_A__c, Question__r.Choice_B__c, Question__r.Choice_C__c, Question__r.Choice_D__c, Question__r.Choice_E__c, Question__r.Question_Text__c, Question__r.RecordType.Name, Question__r.Questionfor__c, Question__r.CorrectAnswer__c
            FROM SurveyJoinQuestion__c
            WHERE Survey__r.Id = :surveyResponse.Survey__c
        ];
        //List<Question__c> questions = new List<Question__c>();
        for(SurveyJoinQuestion__c j : joins){
            questions.add(j.Question__r);
        }

        List<Answers__c> existingAnswers = [
                SELECT Id, Question__c, TextfieldAnswer__c
                FROM Answers__c
                WHERE SurveyResponse__c = :surveyResponse.Id
        ];
        Map<Id, Answers__c> existingAnswersByQuestionId = new Map<Id, Answers__c>();
        for(Answers__c answer : existingAnswers){
            existingAnswersByQuestionId.put(answer.Question__c, answer);
        }

        for(Question__c q : questions) {
            Answers__c answer;
            if (existingAnswersByQuestionId.containsKey(q.Id)) {
                answer = existingAnswersByQuestionId.get(q.Id);
            
                if (q.RecordType.Name == MULTIPLE_CHOICE_TYPE) {
                    //List<String> selectedChoices = answer.MultipleChoiceOutput__c.split(',');
                    List<String> selectedChoices = answer.TextfieldAnswer__c.split('\\|');
                    selectedOptionsByQuestionId.put(q.Id, selectedChoices);
                } else {
                    if(answer.TextfieldAnswer__c != null)
                        responseByQuestionId.put(q.Id, answer.TextfieldAnswer__c);
                }
            }
        }
    }

    public Component.Apex.PageBlock getResponsePage(){
   
        Component.Apex.PageBlock dynPageBlock = new Component.Apex.PageBlock();
        integer counter = 1;
        // creates labels and inputs for each question
        for (Question__c q : questions) {
            //Question__c q = a.Question__r;
            String questionType = q.RecordType.Name;

            Component.Apex.OutputLabel theQuestionLabel = new Component.Apex.OutputLabel();
            theQuestionLabel.value = String.valueof(counter)+'. '+ q.Question_Text__c;
            theQuestionLabel.styleClass = 'questions';
            dynPageBlock.childComponents.add(theQuestionLabel);
            
            /**
             * Used for when the user did not fill out the survey
             */
            if(true || !isFilled){
                if(/*questionType != MULTIPLE_CHOICE_TYPE && */!responseByQuestionId.containsKey(q.Id) || responseByQuestionId.get(q.Id) == null) {
                    responseByQuestionId.put(q.Id, ''); // must have value or will get error
                }
                if(questionType == MULTIPLE_CHOICE_TYPE && !selectedOptionsByQuestionId.containsKey(q.Id)){
                    selectedOptionsByQuestionId.put(q.Id, new List<String>()); // must be initialized or will get error
                }
            }
            if (questionType == TEXT_TYPE) {
                Component.Apex.InputTextArea theInput = new Component.Apex.InputTextArea();
                dynPageBlock.childComponents.add(theInput);
                theInput.styleClass = 'choices';
                theInput.disabled = true;
                if(isFilled){
                    theInput.value = responseByQuestionId.get(q.Id);
                }
                theInput.required = true;

            } else if (questionType == TRUE_FALSE_TYPE) {
                //TODO: add reset button
                Component.Apex.SelectRadio theInput = new Component.Apex.SelectRadio();
                theInput.expressions.value = '{!responseByQuestionId["'+q.Id+'"]}';
                theInput.styleClass = 'choices';
                theInput.required = true;
                theInput.disabled = true;
                List<String> availableOptions = getQuestionChoices(q);
                List<SelectOption> selectOptions = new List<SelectOption>();
                
                for(String choice : availableOptions){
                    SelectOption op = new SelectOption(choice, choice);
                    selectOptions.add(op);
                }
                availableOptionsByQuestionId.put(q.Id, selectOptions);

                Component.Apex.SelectOptions selectOptionsComponent = new Component.Apex.SelectOptions();
                selectOptionsComponent.expressions.value = '{!availableOptionsByQuestionId["'+q.Id+'"]}';
                theInput.childComponents.add(selectOptionsComponent);

                dynPageBlock.childComponents.add(theInput);
                
                
                
            } else if (questionType == RADIO_TYPE ) {
                Component.Apex.SelectRadio theInput = new Component.Apex.SelectRadio();
                theInput.expressions.value = '{!responseByQuestionId["'+q.Id+'"]}';
                theInput.styleClass = 'choices';
                theInput.required = true;
                theInput.disabled = true;
                
                //test values only:
                List<String> availableOptions = getQuestionChoices(q);
                List<SelectOption> selectOptions = new List<SelectOption>(); // to be used instead of seelctoption component list
                //responseByQuestionId.put(q.Id, 'apple');
                for(String choice : availableOptions){
                    SelectOption op = new SelectOption(choice, choice);
                    selectOptions.add(op);
                }
                availableOptionsByQuestionId.put(q.Id, selectOptions);

                Component.Apex.SelectOptions selectOptionsComponent = new Component.Apex.SelectOptions();
                selectOptionsComponent.expressions.value = '{!availableOptionsByQuestionId["'+q.Id+'"]}';
                theInput.childComponents.add(selectOptionsComponent);

                dynPageBlock.childComponents.add(theInput);
                
                
                
                
            } else if (questionType == MULTIPLE_CHOICE_TYPE) {
                Component.Apex.SelectCheckboxes theInput = new Component.Apex.SelectCheckboxes();
                List<String> availableOptions = getQuestionChoices(q);//new List<String>{'apple', 'banana', 'carrot'};

                if(isFilled){
                    theInput.expressions.value = '{!selectedOptionsByQuestionId["'+q.Id+'"]}';
                    
                }else{
                    selectedOptionsByQuestionId.put(q.id,availableOptions);
                }
                theInput.styleClass = 'choices';
                theInput.required = true;
                theInput.disabled = true;
                //test values only:
                
                List<SelectOption> selectOptions = new List<SelectOption>(); // to be used instead of seelctoption component list
                //responseByQuestionId.put(q.Id, 'apple');
                for(String choice : availableOptions){
                    SelectOption op = new SelectOption(choice, choice);
                    selectOptions.add(op);
                }
                availableOptionsByQuestionId.put(q.Id, selectOptions);

                Component.Apex.SelectOptions selectOptionsComponent = new Component.Apex.SelectOptions();
                selectOptionsComponent.expressions.value = '{!availableOptionsByQuestionId["'+q.Id+'"]}';
                theInput.childComponents.add(selectOptionsComponent);

                dynPageBlock.childComponents.add(theInput);
            }
            
            
            if(q.Questionfor__c == 'Exam'){
            	
            	
            	Component.Apex.OutputText CorrectAnswerLabel = new Component.Apex.OutputText();
		        CorrectAnswerLabel.value = 'Correct Answer: ' + q.CorrectAnswer__c;
		        //theQuestionLabel.styleClass = 'correctanswer';
		        
		        
		        dynPageBlock.childComponents.add(CorrectAnswerLabel);
		        		        
            }
            
            counter++;
        }
        
        return dynPageBlock;
    }
    
        /**
    * @description Utility method that returns available choices for a question
    * @param question the Question__c record to get choices for
    * @return a list of choices as strings
    */
    @TestVisible
    private List<String> getQuestionChoices(Question__c question){
        List<String> choices = new List<String>();

        if(question.RecordType.Name == TRUE_FALSE_TYPE){
            return new List<String>{'True', 'False'};
        }

        if(question.Choice_A__c != null)
            choices.add(question.Choice_A__c);
        if(question.Choice_B__c != null)
            choices.add(question.Choice_B__c);
        if(question.Choice_C__c != null)
            choices.add(question.Choice_C__c);
        if(question.Choice_D__c != null)
            choices.add(question.Choice_D__c);
        if(question.Choice_E__c != null)
            choices.add(question.Choice_E__c);

        return choices;
    }
    
}