src/objects/Answers__c.object
<CustomObject>
    <fields>
        <fullName>CorrectAnswer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Correct Answer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyResponse__c</fullName>
        <label>Survey Response</label>
        <referenceTo>SurveyResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Choice_A__c</fullName>
        <label>Choice A</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_B__c</fullName>
        <label>Choice B</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_C__c</fullName>
        <label>Choice C</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_D__c</fullName>
        <label>Choice D</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_E__c</fullName>
        <label>Choice E</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CorrectAnswer__c</fullName>
        <description>The correct answer for the exam question</description>
        <label>Correct Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questionfor__c</fullName>
        <description>Pick list field to determine what the question is for. Example: Survey question or exam question</description>
        <label>Question for</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Exam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Radio</fullName>
        <active>true</active>
        <label>Radio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>NumberofMinutes__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of time in minutes a user has to finish the exam</description>
        <label>Number of Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberofQuestions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of questions the test taker will see</description>
        <label>Number of Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Randomized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If select, the questions on the exam will be displayed in a random order</description>
        <label>Randomized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowOneQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, the user responding to the survey will be given one question per page</description>
        <label>Show One Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowScore__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, the user who responds to this survey will be able to view his/her score</description>
        <label>Show Score</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Surveys Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>Exam</fullName>
        <active>true</active>
        <description>A survey record type that represents an exam format</description>
        <label>Exam</label>
    </recordTypes>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <description>the default record type for survey</description>
        <label>Survey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyJoinQuestion__c.object
<CustomObject>
    <description>The junction object between the survey object and question object</description>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Junction</relationshipLabel>
        <relationshipName>QuestionJunction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Junction</relationshipLabel>
        <relationshipName>SurveyJunction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Join Question</label>
    <nameField>
        <displayFormat>SJQ-{00000000}</displayFormat>
        <label>Survey Join Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Join Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExamPageControllerTest.cls
@isTest
public class ExamPageControllerTest {
    
	@TestSetup static void setup(){
        
    
        List<Question__c> lstQues = new List<Question__c>();
        List<SurveyJoinQuestion__c> listJunc = new List<SurveyJoinQuestion__c>();
        
        /*
         * Creates two test contacts: one to be emailed and one to be deleted 
         */
        Contact testUser = new Contact(FirstName='test',LastName='user',email='testuser@test.com');
        insert testUser;
           

        /*
         * Creates test exam
         */ 
        
		Survey__c exam1 = new Survey__c(name='test exam 1',
			RecordTypeId=Schema.SObjectType.Survey__c.getRecordTypeInfosByName().get('Exam').getRecordTypeId(),
			Randomized__c = true,
			ShowOneQuestion__c = true,
			NumberofMinutes__c = 20,
			ShowScore__c = true,
			NumberofQuestions__c = 0
		);
		
	    Survey__c exam2 = new Survey__c(name='test exam 2',
			RecordTypeId=Schema.SObjectType.Survey__c.getRecordTypeInfosByName().get('Exam').getRecordTypeId(),
			Randomized__c = true,
			ShowOneQuestion__c = true,
			NumberofMinutes__c = 20,
			ShowScore__c = true,
			NumberofQuestions__c = 1
		);
		
        insert exam1;
        insert exam2;
        
        
        
        /*
         * Creates a Survey response object
         */
        
        SurveyResponse__c resp = new SurveyResponse__c(Survey__c = exam1.id, Contact__c = testUser.id);
        SurveyResponse__c testresp = new SurveyResponse__c(Survey__c = exam2.id, Contact__c = testUser.id);
        
        insert resp;
        insert testresp;
        
        /*
         * Create four questions true/false,radio button, open ended, and multiple choice
         */
        
        //true or false
        Question__c testQuestion = new Question__c(
    		RecordTypeId=Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('True/False').getRecordTypeId(),
    		CorrectAnswer__c='True',
    		Questionfor__c = 'Exam',
            Question_Text__c='True or false question');
        lstQues.add(testQuestion);
        
        //radio button
        testQuestion = new Question__c(
            RecordTypeId=Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('Radio').getRecordTypeId(),
            Questionfor__c = 'Exam',
            CorrectAnswer__c='B',
            Question_Text__c='Radio button question',
            Choice_A__c = 'Choice A',
            Choice_B__c = 'Choice B',
            Choice_C__c = 'Choice C',
            Choice_D__c = 'Choice D',
            Choice_E__c = 'Choice E'); 
		lstQues.add(testQuestion);
        
        
        //multiple choice
        testQuestion = new Question__c(
            RecordTypeId=Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('Multiple Choice').getRecordTypeId(),
            Questionfor__c = 'Exam',
            CorrectAnswer__c='B|C|D',
            Question_Text__c='Multiple Choice question',
            Choice_A__c = 'Choice A',
            Choice_B__c = 'Choice B',
            Choice_C__c = 'Choice C',
            Choice_D__c = 'Choice D',
            Choice_E__c = 'Choice E');
    	lstQues.add(testQuestion);
        
        insert lstQues;
        
        /*
         * Create junction object for survey and question
         */ 
        for(integer i = 0;i < lstQues.size();i++){
            listJunc.add(new SurveyJoinQuestion__c(Survey__c=exam1.id,Question__c=lstQues[i].id));
            listJunc.add(new SurveyJoinQuestion__c(Survey__c=exam2.id,Question__c=lstQues[i].id));
        }
        
        insert listJunc;
         
    }
    
    @isTest
    private static void testExam(){
    	
    	
    	Survey__c exam = [select id,name from Survey__c where name = 'test exam 1' limit 1];
    	Survey__c exam2 = [select id,name from Survey__c where name = 'test exam 2' limit 1];
    	Contact examTaker = [select id,name from Contact where FirstName='test' AND LastName='user'];
    	SurveyResponse__c examResp = [select id,name,survey__c,Contact__c from SurveyResponse__c where survey__c =: exam.id AND Contact__c =: examTaker.id];
    	SurveyResponse__c testResp = [select id,name,survey__c,Contact__c from SurveyResponse__c where survey__c =: exam2.id AND Contact__c =: examTaker.id];
       /**
    	* Used to test number of questions selected for the exam
    	*/
    	PageReference testPage = Page.ExamStartPage;
    	testPage.getParameters().put('surveyresponseid',testResp.id);
    	Test.setcurrentPage(testPage); 
    	ExamPageController testController = new ExamPageController();
    	System.assertEquals(1,testController.NumQuestions);
    	

    	
    	
    	
       /**
    	* Testing for exam where all the questions are displayed
    	*/
    	
    	PageReference startPage = Page.ExamStartPage;
    	startPage.getParameters().put('surveyresponseid',examResp.id);
    	Test.setcurrentPage(startPage); 
    	ExamPageController examController = new ExamPageController();
    	System.assertEquals(3,examController.NumQuestions);
    	examcontroller.isOneByOne = false;
    	String pageurl = examcontroller.start().getUrl();
    	System.assertEquals('/apex/exampage',pageurl);
    	examcontroller.getQuestionDynamicForm();
        
        
        
        //Tests the private method getQuestionChoices() with a true/false question and multiple choice question
         
        List<String> choices;
        Question__c multi = [select id,name,RecordType.Name,Choice_A__c,Choice_B__c,Choice_C__c,Choice_D__c,Choice_E__c from Question__c where RecordType.Name = 'Multiple Choice' limit 1];
        Question__c tf = [select id,name,RecordType.Name from Question__c where RecordType.Name = 'True/False' limit 1];
        choices = examcontroller.getQuestionChoices(tf);
        System.assert(choices.size() == 2);
        choices = examcontroller.getQuestionChoices(multi);		//to be used when testing the save() method
        System.assert(choices.size() == 5);
        
        
       /**
        * Testing for exam where questions are displayed one by one
        */
        
        
        examController = new ExamPageController();
        examcontroller.isOneByOne = true;
    	pageurl = examcontroller.start().getUrl();
    	System.assertEquals('/apex/examonebyonepage',pageurl);
        examcontroller.getQuestionOnebyOne();
        
        //testing the buttons
        System.assertEquals(true,examController.getdisabledPrev());
        System.assertEquals(false,examController.getdisabledNext());
        examController.next();
        examcontroller.getQuestionOnebyOne();
        examController.prev();
        examController.next();
        examController.next();
        examcontroller.getQuestionOnebyOne();
        
    	for(Question__c q: examcontroller.questions){
            if(q.RecordType.Name =='True/False'){
                examcontroller.responseByQuestionId.put(q.id,'True');
            }else if(q.RecordType.Name =='Multiple Choice'){
                examcontroller.selectedOptionsByQuestionId.put(q.id,new List<String>{'B|C|D'});
            }else if(q.RecordType.Name =='Radio'){
                examcontroller.responseByQuestionId.put(q.id,q.Choice_B__c);
            }
        }
        String url = examcontroller.submit().getUrl();
        SurveyResponse__c survResp = [select id,name,Survey__c,(Select Id,Name from Answers__r) from SurveyResponse__c limit 1];
        System.assertEquals(3, examcontroller.numCorrectQuestions);
        System.assertEquals('/apex/examscorepage', url);
    	
    	
    }
    
}