src/objects/Answers__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyResponse__c</fullName>
        <label>Survey Response</label>
        <referenceTo>SurveyResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextfieldAnswer__c</fullName>
        <label>TextfieldAnswer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Choice_A__c</fullName>
        <label>Choice A</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_B__c</fullName>
        <label>Choice B</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_C__c</fullName>
        <label>Choice C</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_D__c</fullName>
        <label>Choice D</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Choice_E__c</fullName>
        <label>Choice E</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Surveys Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyJoinQuestion__c.object
<CustomObject>
    <description>The junction object between the survey object and question object</description>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Junction</relationshipLabel>
        <relationshipName>QuestionJunction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Junction</relationshipLabel>
        <relationshipName>SurveyJunction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Join Question</label>
    <nameField>
        <displayFormat>SJQ-{00000000}</displayFormat>
        <label>Survey Join Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Join Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ControllerSurveySummary.cls
public class ControllerSurveySummary {
    public String surveyid{get;set;}
    public String surveyName{get;set;}
    public Survey__c surv{get;set;}
    public Map<Id, QuestionWrapper> questionData{get;set;}

    public ControllerSurveySummary(ApexPages.StandardController stdcontroller){
    	
    	//surv = (Survey__c) stdcontroller.getRecord();
    	surv = [select id,name from Survey__c where id =: stdcontroller.getRecord().id limit 1];
    	surveyid = surv.id;
    	surveyName = surv.Name;
    	
        setupData();
    }

    public void setupData(){

        List<Id> questionIds = new List<Id>();
        List<Question__c> questions = new List<Question__c>();
        List<SurveyJoinQuestion__c> joins = [
            SELECT Id, Question__c FROM SurveyJoinQuestion__c
            WHERE Survey__c = :surveyid
        ];
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'joins: '+joins.size()));

        for(SurveyJoinQuestion__c j : joins){
            questionIds.add(j.Question__c);
        }
        questions = [
            SELECT Id, RecordType.Name, Question_Text__c, Choice_A__c, Choice_B__c, Choice_C__c, Choice_D__c, Choice_E__c
            FROM Question__c
            WHERE Id IN :questionIds AND RecordType.Name != 'Short Answer'
        ];
        List<AggregateResult> totals = [
            SELECT Question__c, COUNT(Id) cnt, TextFieldAnswer__c
            FROM Answers__c
            WHERE Question__c IN :questions AND SurveyResponse__r.Survey__c = :surveyId
            GROUP BY Question__c, TextFieldAnswer__c
        ];
        questionData = new Map<Id, QuestionWrapper>();

        for(Question__c q : questions){
            questionData.put(q.Id, new QuestionWrapper(q));
        }

        for(AggregateResult r : totals){
            questionData.get((Id)r.get('Question__c')).choicesTotals.put((String)r.get('TextFieldAnswer__c'), (Integer)r.get('cnt'));
        }
    }

    public String getJSONResults(){
        if(questionData != null)
            return JSON.serialize(questionData.values());
        return null;
    }
    public List<QuestionWrapper> getResults(){
        if(questionData != null)
            return questionData.values();
        return null;
    }

    private class QuestionWrapper{
        public Id id{get;set;}
        public String text{get;set;}
        public String recordType{get;set;}
        public Map<String, Integer> choicesTotals{get;set;}

        public QuestionWrapper(Question__c question){
            id = question.Id;
            text = question.Question_Text__c;
            recordType = question.RecordType.Name;
            choicesTotals = new Map<String, Integer>();

            if(question.RecordType.Name == 'True/False'){
                choicesTotals.put('True', 0);
                choicesTotals.put('False', 0);
            }

            if(question.Choice_A__c != null)
                choicesTotals.put(question.Choice_A__c, 0);
            if(question.Choice_B__c != null)
                choicesTotals.put(question.Choice_B__c, 0);
            if(question.Choice_C__c != null)
                choicesTotals.put(question.Choice_C__c, 0);
            if(question.Choice_D__c != null)
                choicesTotals.put(question.Choice_D__c, 0);
            if(question.Choice_E__c != null)
                choicesTotals.put(question.Choice_E__c, 0);
        }
    }
}